---
name: Dispatch-Declare
version: v0.0.5
author:
  - 'Robert Boone <rlb@cpan.org>'
abstract: Build a hash based dispatch table declaratively
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
  version: 0
provides:
  Dispatch::Declare:
    file: lib/Dispatch/Declare.pm
    version: v0.0.5
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
